[tool.poetry]
name = "electronics-shop-project-av"
version = "0.1.0"
description = ""
authors = ["avedineev <avedineev69@gmail.com>"]
readme = "README.md"
packages = [{ include = "electronics_shop_project_av" }]

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^7.3.1"


[tool.poetry.group.dev.dependencies]
pytest-cov = "^4.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
