[tool.poetry]
name = "hw_13"
version = "0.1.0"
description = ""
authors = ["Artem Osipov <tema.osipov@mail.ru>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
