[tool.poetry]
name = "electronics-shop-project"
version = "0.1.0"
description = ""
authors = ["Artemii Dovzhenko <rockenny@ymail.com>"]
readme = "README.md"
packages = [{include = "electronics_shop_project"}]

[tool.poetry.dependencies]
python = "^3.11"


[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
coverage = "^7.2.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
